# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'MyText' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for MyText

    pod 'MBProgressHUD', '~> 0.9.2'
    pod 'AFNetworking', '~> 3.1.0'
    pod 'SDAutoLayout', '~> 1.31'
    pod 'SDCycleScrollView', '~> 1.61'
    pod 'GPUImage', '~> 0.1.7'
    pod 'AliyunOSSiOS', '~> 2.4.1'
    pod 'ReactiveCocoa'
    pod 'GPUImage', '~> 0.1.7'
    pod 'CocoaSecurity', '~> 1.2.4'
    pod 'NSLogger'
    pod 'UMeng', '~> 2.2.1'
    pod 'MJExtension', '~> 3.0.13'


  target 'MyTextTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MyTextUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
